adres: "Huttelaan 30, 3001 Heverlee"
uren: "Elke zondag van 14u tot 17u30"
facebook: "https://www.facebook.com/ChiroSpiritHeverlee"
instagram: "https://www.instagram.com/chirospiritheverlee"
email_algemeen: "chirospiritheverlee@gmail.com"
email_verhuur: "verhuur.chirospirit@gmail.com"
