adres: Huttelaan 30
uren: 14:00 - 17:30
facebook: https://www.facebook.com/ChiroSpiritHeverlee
instagram: https://www.instagram.com/chirospiritheverlee
email_algemeen: chirospiritheverlee@gmail.com
email_verhuur: verhuur.chirospirit@gmail.com
